Repository Club-PARD/UJaCha_WEB, pull requests merged in 2024-02, with the labels that each got.

#3 style : 메인컬러 theme 추가
  package-lock.json
  package.json
  src/Pages/TestPage/TestPage.js
  src/Styles/theme.js
  src/index.js
Labels: style

#14 test page ui 구현
  src/Pages/TestPage/Components/TestPageAnswer.js
  src/Pages/TestPage/Components/TestPageButton.js
  src/Pages/TestPage/Components/TestPageHeader.js
  src/Pages/TestPage/Components/TestPageQuestion.js
  src/Pages/TestPage/TestPage.js
  src/Pages/TestPage/Utils/Questions.js
Labels: style

#16 style : 프로그레스 바 수정 및 애니메이션 추가
  public/img/check.png
  src/Pages/TestPage/Components/TestHeader.js
  src/Pages/TestPage/Components/TestPageAnswer.js
  src/Pages/TestPage/TestPage.js
Labels: style

#21 테스트 페이지 recoil로 상태관리 변경 및 데이터 전송 오류 해결
  package-lock.json
  package.json
  src/Api/test.js
  src/Atoms.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/ResultPage/ResultPage.js
  src/Pages/TestPage/Components/TestHeader.js
  src/Pages/TestPage/Components/TestLoading.js
  src/Pages/TestPage/Components/TestPageAnswer.js
  src/Pages/TestPage/Components/TestPageButton.js
  src/Pages/TestPage/Components/TestPageQuestion.js
  src/Pages/TestPage/TestPage.js
Labels: fix, feat

#22 fetch : 결과 페이지 구현
  src/App.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/ResultPage/Components/ResultHeader.js
Labels: feat

#23 feat : 테스트 페이지 모달 추가
  src/Layout/Modal.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/TestPage/Components/TestHeader.js
Labels: feat

#26 feat, style : 스타일, 네비세이션 등 수정
  src/Api/test.js
  src/Layout/Modal.js
  src/Pages/LoginPage/SocialKakao.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/ResultPage/Components/ResultHeader.js
  src/Pages/TestPage/Components/TestLoading.js
  src/Pages/TestPage/TestPage.js
Labels: style, feat

#29 feat, style, edit
  src/Api/test.js
  src/Atoms.js
  src/Pages/IntroPage/Components/IntroPageMain.js
  src/Pages/IntroPage/IntroPage.js
  src/Pages/LoginPage/RegisterPage.js
  src/Pages/LoginPage/SocialKakao.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/TestPage/Components/TestLoading.js
  src/Pages/TestPage/Components/TestPageButton.js
  src/Pages/TestPage/TestPage.js
Labels: style, feat

#33 feat : 마이페이지 구현
  public/img/chevron-right.png
  public/img/pencil-line.png
  src/MyRoutes.js
  src/Pages/MyPage/Components/Account.js
  src/Pages/MyPage/Components/Header.js
  src/Pages/MyPage/Components/Record.js
  src/Pages/MyPage/Components/UserInfo.js
  src/Pages/MyPage/MyPage.js
  src/Pages/TestPage/TestPage.js
Labels: style, feat

#37 fix, style : 버튼 버그, 스타일 조정
  public/index.html
  src/Layout/Layout.js
  src/Layout/Modal.js
  src/Pages/CommunityPage/CommunityPage.js
  src/Pages/IntroPage/Components/IntroPageMain.js
  src/Pages/LoginPage/RegisterPage.js
  src/Pages/LoginPage/SocialKakao.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/ResultPage/ResultPage.js
  src/Pages/TestPage/Components/TestLoading.js
  src/Pages/TestPage/Components/TestPageAnswer.js
  src/Pages/TestPage/Components/TestPageButton.js
  src/Pages/TestPage/Components/TestPageQuestion.js
  src/Pages/TestPage/TestPage.js
Labels: fix, style

#38 style: 커서 포인터 추가
  src/Layout/Layout.js
  src/Pages/HomePage/HomePage.js
  src/Pages/IntroPage/Components/IntroPageHeader.js
  src/Pages/IntroPage/Components/IntroPageMain.js
  src/Pages/LoginPage/SocialKakao.js
  src/Pages/ResultPage/Components/ResultContents.js
  src/Pages/ResultPage/Components/ResultHeader.js
  src/Pages/TestPage/Components/TestHeader.js
  src/Pages/TestPage/Components/TestPageButton.js
Labels: style

#43 edit, fix : 데이터 수정 및 로그인 버그 해결
  src/Api/test.js
  src/Atoms.js
  src/Pages/HomePage/HomePage.js
  src/Pages/LoginPage/RegisterPage.js
Labels: fix

#44 feat : 증상 추가하기의 데이터 유무 여부 모달창
  src/Api/test.js
  src/Layout/Modal.js
  src/Pages/HomePage/HomePage.js
Labels: feat

#45 fix : 증상 추가하고 갑자기 결과페이지로 가는 버그 해결
  src/Api/test.js
  src/Pages/ResultPage/ResultPage.js
  src/Pages/TestPage/Components/TestLoading.js
Labels: fix

#46 style : 버튼 hover 스타일 추가
  src/Pages/IntroPage/Components/IntroPageMain.js
  src/Pages/LoginPage/SocialKakao.js
  src/Pages/TestPage/Components/TestPageButton.js
  src/Styles/theme.js
Labels: style

#48 style : 테스트 에니메이션 오류 해결
  src/Pages/TestPage/TestPage.js
Labels: style

#53 feat : 탈퇴기능 구현
  src/Layout/Modal.js
  src/Pages/IntroPage/IntroPage.js
  src/Pages/MyPage/Components/Account.js
  src/Pages/TestPage/Components/TestHeader.js
Labels: style, feat

#54 feat : 사용자 유무에 따른 마이페이지 버튼 활성화
  src/Pages/MyPage/Components/Header.js
  src/Pages/TestPage/Components/TestHeader.js
Labels: fix, style

#58 feat, style : 버튼 활성화, css 조정
  src/Layout/Modal.js
  src/Pages/ResultPage/Components/ResultHeader.js
  src/Pages/TestPage/Components/TestPageButton.js
  src/Pages/TestPage/Utils/Questions.js
Labels: style, feat

#60 style : 배경색 변경
  src/Pages/LoginPage/RegisterPage.js
Labels: style

#65 edit : HomePage 주석 추가
  src/Pages/HomePage/HomePage.js
Labels: fix

#66 Pangil
  src/Layout/Header.js
  src/Pages/CommunityPage/CommunityPageAddPost/CommunityPageAddPost.js
Labels: style, edit

#69 edit : Modal2 컴포넌트 최적화 및 리팩토링
  src/Layout/Modal2.js
Labels: edit

#71 edit : 모듈화 및 warning 오류 해결
  src/Layout/Header.js
  src/Layout/Layout.js
  src/Layout/Modal2.js
  src/Pages/CommunityPage/Components/CommunityPageContent.js
  src/Pages/CommunityPage/Components/CommunityPageSearch.js
  src/Pages/HomePage/Components/HomePageChartResult.js
  src/Pages/HomePage/HomePage.js
Labels: edit

#72 add : 파비콘 이미지 추가 변경
  public/index.html
  public/mainLogo.png
Labels: style, add

#73 edit : Warning Solved and HomePage 분리
  src/Pages/HomePage/HomePage.js
  src/Pages/IntroPage/Components/IntroPageBottom.js
  src/Pages/IntroPage/Components/IntroPageContent.js
  src/Pages/IntroPage/Components/IntroPageMain.js
  src/Pages/LoginPage/SocialKakao.js
  src/Pages/MyPage/Components/Record.js
  src/Pages/MyPage/Components/UserInfo.js
Labels: edit
